[versions]
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
ktor = "3.3.1"
compose = "1.9.1"
mockk = "1.14.6"
sqldelight = "2.2.1"
koin = "4.1.1"
koin-annotations = "2.3.1"
ksp = "2.3.0"
okio = "3.16.2"
detekt = "1.23.8"
detekt-compose = "0.4.27"
kover = "0.9.3"
shadowJar = "9.2.2"
inmo-tgbotapi = "30.0.0"
exposed = "1.0.0-rc-3"
testcontainers = "1.21.3"
postgresql-r2dbc = "1.1.1.RELEASE"
r2dbc = "1.0.0.RELEASE"

[libraries]
# ───────────────────────────────────────────────────────────────────────────────
# KotlinX Libraries
# ───────────────────────────────────────────────────────────────────────────────
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# ───────────────────────────────────────────────────────────────────────────────
# Ktor Libraries
# ───────────────────────────────────────────────────────────────────────────────
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# ───────────────────────────────────────────────────────────────────────────────
# Testing Libraries
# ───────────────────────────────────────────────────────────────────────────────
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# ───────────────────────────────────────────────────────────────────────────────
# Telegram Bot API
# ───────────────────────────────────────────────────────────────────────────────
inmo-tgbotapi-core = { module = "dev.inmo:tgbotapi.core", version.ref = "inmo-tgbotapi" }
inmo-tgbotapi-extensions = { module = "dev.inmo:tgbotapi.api", version.ref = "inmo-tgbotapi" }
inmo-tgbotapi-utils = { module = "dev.inmo:tgbotapi.utils", version.ref = "inmo-tgbotapi" }
inmo-tgbotapi = { module = "dev.inmo:tgbotapi", version.ref = "inmo-tgbotapi" }

# ───────────────────────────────────────────────────────────────────────────────
# Database
# ───────────────────────────────────────────────────────────────────────────────
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-time = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }

r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version.ref = "postgresql-r2dbc" }
r2dbc-spi = { module = "io.r2dbc:r2dbc-spi", version.ref = "r2dbc" }

sqldelight-jvm-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
h2-database = { module = "com.h2database:h2", version.require = "2.2.224" }

# ───────────────────────────────────────────────────────────────────────────────
# DI - Koin
# ───────────────────────────────────────────────────────────────────────────────
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

# ───────────────────────────────────────────────────────────────────────────────
# Misc / Core Libraries
# ───────────────────────────────────────────────────────────────────────────────
squareup-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# ───────────────────────────────────────────────────────────────────────────────
# Build Plugins Classpaths (for `build-conventions`) module
# ───────────────────────────────────────────────────────────────────────────────
pluginClasspath-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
pluginClasspath-sqldelight = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
pluginClasspath-compose = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
pluginClasspath-compose-compiler = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
pluginClasspath-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
pluginClasspath-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
pluginClasspath-kover = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }
pluginClasspath-shadowJar = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version.ref = "shadowJar" }

# ───────────────────────────────────────────────────────────────────────────────
# Detekt
# ───────────────────────────────────────────────────────────────────────────────
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }

# ───────────────────────────────────────────────────────────────────────────────
# Test containers (Docker)
# ───────────────────────────────────────────────────────────────────────────────
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers"}

[plugins]
# ───────────────────────────────────────────────────────────────────────────────
# Kotlin
# ───────────────────────────────────────────────────────────────────────────────
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# ───────────────────────────────────────────────────────────────────────────────
# Kotlin Compiler Plugins
# ───────────────────────────────────────────────────────────────────────────────
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# ───────────────────────────────────────────────────────────────────────────────
# Compose
# ───────────────────────────────────────────────────────────────────────────────
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

# ───────────────────────────────────────────────────────────────────────────────
# Database / SQLDelight
# ───────────────────────────────────────────────────────────────────────────────
cashapp-sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

# ───────────────────────────────────────────────────────────────────────────────
# KSP
# ───────────────────────────────────────────────────────────────────────────────
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# ───────────────────────────────────────────────────────────────────────────────
# Code Quality
# ───────────────────────────────────────────────────────────────────────────────
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# ───────────────────────────────────────────────────────────────────────────────
# Packaging & Build
# ───────────────────────────────────────────────────────────────────────────────
shadowJar = { id = "com.gradleup.shadow", version.ref = "shadowJar" }
